### ISSUE TITLE
声卡不工作

### ISSUE THREAD

**Issue by gushandujian** [likidu/opencore-7080-mff#1]
咱俩主机型号一样，CPU一样，主板芯片一样，声卡也是ALC256，我的声卡就是不工作，其他正常，我对OC不熟，我的做法是增加lilu.kext和applealc.kext，还有就是在config里面添加			
<key>PciRoot(0x0)/Pci(0x1F,0x3)</key>
			<dict>
				<key>alc-layout-id</key>
				<data>FQAAAA==</data>
				<key>device_type</key>
				<string>Audio device</string>
				<key>model</key>
				<string>Realtek ALC256</string>
			</dict>
why?

**Comment by likidu** [comment]
你`boot-args`里面没有设置关于声卡的东西吧。另外可以把你的config和我的做个diff看看有什么地方有区别。
