### ISSUE TITLE
请问BCM94352Z M.2是直接替换原来的201吗 

### ISSUE THREAD

**Issue by glarer** [likidu/opencore-7080-mff#2]
主板莫非其实支持cnvi+ngff？

**Comment by likidu** [comment]
是直接替换的，淘宝上找一个M.2的94352Z直接换掉AX201就可以。然后WiFi无需驱动就可以用。当然需要加载几个BCM蓝牙的Kext.

**Comment by glarer** [comment]
OKOK thanks 我装上好几天了 现在发现是免驱 这块卡还是有点垃圾



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Liki Du <notifications@github.com&gt;
发送时间: 2020年12月27日 12:32
收件人: likidu/opencore-7080-mff <opencore-7080-mff@noreply.github.com&gt;
抄送: BiYX <931160120@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[likidu/opencore-7080-mff] 请问BCM94352Z M.2是直接替换原来的201吗  (#2)

**Comment by likidu** [comment]
性能肯定比不过AX201，但Intel现在驱动问题还太多了。暂时先凑合用吧。
